/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FindRouteImport } from './routes/find'
import { Route as MapRouteImport } from './routes/map'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as UssdRouteImport } from './routes/ussd'
import { Route as ApiPlacePhotoRouteImport } from './routes/api/place-photo'
import { Route as FacilityFacilityIdRouteImport } from './routes/facility.$facilityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const UssdRoute = UssdRouteImport.update({
  id: '/ussd',
  path: '/ussd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacePhotoRoute = ApiPlacePhotoRouteImport.update({
  id: '/api/place-photo',
  path: '/api/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityFacilityIdRoute = FacilityFacilityIdRouteImport.update({
  id: '/facility/$facilityId',
  path: '/facility/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/find': typeof FindRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/ussd': typeof UssdRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/facility/$facilityId': typeof FacilityFacilityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/find': typeof FindRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/ussd': typeof UssdRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/facility/$facilityId': typeof FacilityFacilityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/find': typeof FindRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/ussd': typeof UssdRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/facility/$facilityId': typeof FacilityFacilityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/emergency'
    | '/find'
    | '/map'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/ussd'
    | '/api/place-photo'
    | '/facility/$facilityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/emergency'
    | '/find'
    | '/map'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/ussd'
    | '/api/place-photo'
    | '/facility/$facilityId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/emergency'
    | '/find'
    | '/map'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/ussd'
    | '/api/place-photo'
    | '/facility/$facilityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  EmergencyRoute: typeof EmergencyRoute
  FindRoute: typeof FindRoute
  MapRoute: typeof MapRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  UssdRoute: typeof UssdRoute
  ApiPlacePhotoRoute: typeof ApiPlacePhotoRoute
  FacilityFacilityIdRoute: typeof FacilityFacilityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ussd': {
      id: '/ussd'
      path: '/ussd'
      fullPath: '/ussd'
      preLoaderRoute: typeof UssdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-photo': {
      id: '/api/place-photo'
      path: '/api/place-photo'
      fullPath: '/api/place-photo'
      preLoaderRoute: typeof ApiPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/$facilityId': {
      id: '/facility/$facilityId'
      path: '/facility/$facilityId'
      fullPath: '/facility/$facilityId'
      preLoaderRoute: typeof FacilityFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  EmergencyRoute: EmergencyRoute,
  FindRoute: FindRoute,
  MapRoute: MapRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  UssdRoute: UssdRoute,
  ApiPlacePhotoRoute: ApiPlacePhotoRoute,
  FacilityFacilityIdRoute: FacilityFacilityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
